### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by HCideal** [salesforce/awd-lstm-lm#111]
python3 -u main.py --epochs 50 --nlayers 3 --emsize 400 --nhid 1840 --alpha 0 --beta 0 --dropoute 0 --dropouth 0.1 --dropouti 0.1 --dropout 0.4 --wdrop 0.2 --wdecay 1.2e-6 --bptt 200 --batch_size 128 --optimizer adam --lr 1e-3 --data data/enwik8 --save ENWIK8.pt --when 25 35
Producing dataset...
Traceback (most recent call last):
  File "main.py", line 100, in <module>
    corpus = data.Corpus(args.data)
  File "/home/swee/Desktop/awd-lstm-lm-master/data.py", line 30, in __init__
    self.train = self.tokenize(os.path.join(path, 'train.txt'))
  File "/home/swee/Desktop/awd-lstm-lm-master/data.py", line 36, in tokenize
    assert os.path.exists(path)
AssertionError

**Comment by jabraunlin** [comment]
You need to execute the getdata.sh file: 
`chmod 755 getdata.sh`
`./getdata.sh`
