### ISSUE TITLE
TypeError: cannot assign 'torch.cuda.FloatTensor' as parameter 'weight_hh_l0' (torch.nn.Parameter or None expected)

### ISSUE THREAD

**Issue by Sahar-Abdelnabi** [salesforce/awd-lstm-lm#114]
Hi, 

I am getting this error after the model finishes one epoch. This is the full stack trace:

Traceback (most recent call last):
  File "main.py", line 240, in <module>
    train()
  File "main.py", line 196, in train
    output, hidden, rnn_hs, dropped_rnn_hs = model(data, hidden, return_h=True)
  File "/home/sahar.abdelnabi/anaconda3/envs/new_py/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sahar.abdelnabi/awd_lstm_lm/model.py", line 83, in forward
    raw_output, new_h = rnn(raw_output, hidden[l])
  File "/home/sahar.abdelnabi/anaconda3/envs/new_py/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sahar.abdelnabi/awd_lstm_lm/weight_drop.py", line 46, in forward
    self._setweights()
  File "/home/sahar.abdelnabi/awd_lstm_lm/weight_drop.py", line 43, in _setweights
    setattr(self.module, name_w, w)
  File "/home/sahar.abdelnabi/anaconda3/envs/new_py/lib/python3.7/site-packages/torch/nn/modules/module.py", line 610, in __setattr__
    .format(torch.typename(value), name))
TypeError: cannot assign 'torch.cuda.FloatTensor' as parameter 'weight_hh_l0' (torch.nn.Parameter or None expected)

I am not sure if this is related to #79, but I tried the fix there and it did not solve the error.

I am using python 3.7.6 and I installed pytorch on anaconda as follows:
conda install pytorch==1.2.0 torchvision==0.4.0 -c pytorch

I also get these warnings, but I am not sure they are related:  UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). 

Could you please help me with this?

Thanks a lot

**Comment by Sahar-Abdelnabi** [comment]
I found that I did not add (torch.nn.Parameter) to the dropout call in the else statement. I edited as follows and it worked. Thanks a lot.

                w = torch.nn.Parameter(mask.expand_as(raw_w) * raw_w)
            else:
                w = torch.nn.Parameter(torch.nn.functional.dropout(raw_w, p=self.dropout, training=self.training))
