### ISSUE TITLE
Fine-tune broken for QRNNs?

### ISSUE THREAD

**Issue by daemon** [salesforce/awd-lstm-lm#28]
I made some modifications to the codebase, so this might be a problem on my end... But does `finetune.py` require `SplitCrossEntropyLoss` to be used for the criterion instead? The decoder is called in `SplitCrossEntropyLoss` only. I added the appropriate `SplitCrossEntropyLoss` in `finetune.py`, and it works as expected.

**Comment by Smerity** [comment]
Finetune is currently broken - I forgot to update that code when updating `main.py`.

See https://github.com/salesforce/awd-lstm-lm/issues/26

I'll close this when I've fixed the issue.

**Comment by soyoung97** [comment]
Hi @daemon, I'm trying to work this finetune.py out.  Can you tell me what you changed to make this work? I imported SplitCrossEntropyLoss and changed criterion on https://github.com/salesforce/awd-lstm-lm/blob/master/finetune.py#L115 and https://github.com/salesforce/awd-lstm-lm/blob/master/finetune.py#L146 to ```SplitCrossEntropyLoss(...)```
and changed the torch.load(f) on https://github.com/salesforce/awd-lstm-lm/blob/master/finetune.py#L177 to
``` model, _, _ = torch.load(f) ``` ,
but this still gives me an error.
Any help would be greatly appreciated!

**Comment by soyoung97** [comment]
The errors are the following:
```
Traceback (most recent call last):                                                                         
  File "finetune.py", line 186, in <module>                                                                
    stored_loss = evaluate(val_data)                                                                       
  File "finetune.py", line 119, in evaluate                                                                
    total_loss += len(data) * SplitCrossEntropyLoss(output_flat, targets).data                             
  File "/workspace/awd-lstm-lm/splitcross.py", line 16, in __init__                                        
    self.splits = [0] + splits + [100 * 1000000]                                                           
TypeError: add() received an invalid combination of arguments - got (list), but expected one of:            
 * (Tensor other, Number alpha)                                                                            
 * (Number other, Number alpha)  ```
